//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLoadTest.SapIDocGenerator.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLoadTest.SapIDocGenerator.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonTitle {
            get {
                return ResourceManager.GetString("CancelButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  IDoc parameter has been copied to clipboard.
        /// </summary>
        public static string CopiedToClipboardPopupText {
            get {
                return ResourceManager.GetString("CopiedToClipboardPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string CopyReplaceButtonCopyModeTitle {
            get {
                return ResourceManager.GetString("CopyReplaceButtonCopyModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string CopyReplaceButtonReplaceModeTitle {
            get {
                return ResourceManager.GetString("CopyReplaceButtonReplaceModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonTitle {
            get {
                return ResourceManager.GetString("CreateButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C header files (*.h)|*.h.
        /// </summary>
        public static string DefinitionFilePathSelectionControlFilter {
            get {
                return ResourceManager.GetString("DefinitionFilePathSelectionControlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open IDoc Definition File.
        /// </summary>
        public static string DefinitionFilePathSelectionControlTitle {
            get {
                return ResourceManager.GetString("DefinitionFilePathSelectionControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDoc text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string ExampleFilePathSelectionControlFilter {
            get {
                return ResourceManager.GetString("ExampleFilePathSelectionControlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Example IDoc file.
        /// </summary>
        public static string ExampleFilePathSelectionControlTitle {
            get {
                return ResourceManager.GetString("ExampleFilePathSelectionControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string ImportButtonContent {
            get {
                return ResourceManager.GetString("ImportButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string ImportPathSelectionControlFilter {
            get {
                return ResourceManager.GetString("ImportPathSelectionControlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportTabHeader {
            get {
                return ResourceManager.GetString("ImportTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Type....
        /// </summary>
        public static string NewTypeButtonContent {
            get {
                return ResourceManager.GetString("NewTypeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C header files|*.h.
        /// </summary>
        public static string NewTypePathSelectionControlFilter {
            get {
                return ResourceManager.GetString("NewTypePathSelectionControlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ParametersTabHeader {
            get {
                return ResourceManager.GetString("ParametersTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text has been replaced with the IDoc parameter.
        /// </summary>
        public static string ReplacedWithParameterPopupText {
            get {
                return ResourceManager.GetString("ReplacedWithParameterPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository path is not selected.
        /// </summary>
        public static string RepositoryPathNoSelected {
            get {
                return ResourceManager.GetString("RepositoryPathNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS
        ///1. Export the IDoc definition as a C header file and save it to your computer
        ///2. Import the IDoc definition file.
        /// </summary>
        public static string WizardInstructions12 {
            get {
                return ResourceManager.GetString("WizardInstructions12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Import an example IDoc to use as a template.
        /// </summary>
        public static string WizardInstructions3 {
            get {
                return ResourceManager.GetString("WizardInstructions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Generate the VuGen script.
        /// </summary>
        public static string WizardInstructions4 {
            get {
                return ResourceManager.GetString("WizardInstructions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string WizardTabHeader {
            get {
                return ResourceManager.GetString("WizardTabHeader", resourceCulture);
            }
        }
    }
}
